### ISSUE TITLE
[建议]可以用原来的列表选择模型

### ISSUE THREAD

**Issue by BigUncle** [AIGODLIKE/AIGODLIKE-ComfyUI-Studio#11]
最新版的会直接进入到模型的生成的页面，不像原来的可以直接以列表的形式进行快速选择，建议回到上一个版本或者提供一个设置供我们选择。
谢谢。
原版的：
![image](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Studio/assets/9360607/5e17b145-5dc5-4765-8141-9df8147362e2)

**Comment by KarryCharon** [comment]
@BigUncle 最新版 是将原本的下拉选择框调整为了 `Shift + 点击` 的方式

**Comment by BigUncle** [comment]
> @BigUncle 最新版 是将原本的下拉选择框调整为了 `Shift + 点击` 的方式

@KarryCharon 收到。谢谢！

**Comment by BigUncle** [comment]
改成shift+左键 的方式还是不方便，经常会因为单击切换到模型的页面。能否提供一个设置让我们选择哪个方式点击呢？

**Comment by toyxyz** [comment]
I'm changing this line to prevent the model manager from launching when I click on the model list. You can do this by removing the '!' before 'event.shiftKey'. 

https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Studio/blob/1fba59e3f49545282aa4c42e3516dc454fa4bd3e/loader/enterLoader.js#L71

if (event.shiftKey && event.type === LiteGraph.pointerevents_method + "down") {

**Comment by BigUncle** [comment]
> I'm changing this line to prevent the model manager from launching when I click on the model list. You can do this by removing the '!' before 'event.shiftKey'.
> 
> https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Studio/blob/1fba59e3f49545282aa4c42e3516dc454fa4bd3e/loader/enterLoader.js#L71
> 
> if (event.shiftKey && event.type === LiteGraph.pointerevents_method + "down") {
It works.
Thank you very much!!!
