### ISSUE TITLE
除了系统自带的，其他加载器无法正常加载模型

### ISSUE THREAD

**Issue by chdldy** [AIGODLIKE/AIGODLIKE-ComfyUI-Studio#20]
![2024-03-20_11-15-57](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Studio/assets/156064620/af5da733-3c03-4cef-81dc-421ac7508ac3)
![2024-03-20_11-16-52](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Studio/assets/156064620/44485bb6-5a37-4b06-bd40-89cc67421eb1)
![2024-03-20_11-17-00](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Studio/assets/156064620/bff6b524-d9ba-4ac8-baee-f414a46c45ce)
![2024-03-20_11-17-28](https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Studio/assets/156064620/c1232d14-6fbc-4794-b43e-5461e92c8a2e)

可以看到系统自带的加载器可以正常看到模型，但是pysss还有其他一下加载器加载就是空白的。

**Comment by KarryCharon** [comment]
@chdldy pysss 早就修复过了, 你更新最新版了吗

**Comment by KarryCharon** [comment]
> @chdldy pysss 早就修复过了, 你更新最新版了吗

下载develop版

**Comment by chdldy** [comment]
> > @chdldy pysss 早就修复过了, 你更新最新版了吗
> 
> 下载develop版

谢谢，更行后已解决
