### ISSUE TITLE
The ComfyUI-Studio model manager cannot be opened properly

### ISSUE THREAD

**Issue by Github125789** [AIGODLIKE/AIGODLIKE-ComfyUI-Studio#26]
Opening the model Manager on a remote shared access port will result in a black screen, even if you try restarting the launcher. However, it is strange that the local port can be used normally, but the remote shared access port can not be used, I hope to be able to answer the author

**Comment by KarryCharon** [comment]
@Github125789 try the newest version for testing?

**Comment by Github125789** [comment]
Ok, it's settled
