### ISSUE TITLE
comfyui更新后，插件出现了重大BUG！！！，无法打开

### ISSUE THREAD

**Issue by 52Hz-p** [AIGODLIKE/AIGODLIKE-ComfyUI-Studio#44]

**Comment by sa-nny** [comment]
![0](https://github.com/user-attachments/assets/c170d823-a988-4f4f-9287-1ef0eba5054e)
我也遇到了这个情况，更新comfyui后出现+号了，但打不开

**Comment by 7yilink** [comment]
comfyui更新到ts版本后现在发现两个节点不兼容

comfyui-mixlab-nodes
与这个

同样碰到只有+号，然后打不开页面的情况

**Comment by 52Hz-p** [comment]
> 这是ComfyUI更新的问题，得修啊

我去跟cf作者反映下看看，已经离不开咋们这个插件了

**Comment by Yorha4D** [comment]
周一开始维修

**Comment by KarryCharon** [comment]
@52Hz-p @7yilink @sa-nny 
试试最新的develop 分支呢, 修复了ComfyUI 最新前端导致的bug

**Comment by 52Hz-p** [comment]
> @52Hz-p @7yilink @sa-nny 尝试最新的开发分支呢，修复了ComfyUI最新前端导致的bug
ok，我先去试试，因为我在cf作者底下也反映过此问题，但是，被作者直接关闭了，说没时间哈哈

**Comment by 52Hz-p** [comment]
> > @52Hz-p @7yilink @sa-nny尝试最新的开发分支呢，修复了ComfyUI最新前端导致的bug 
> > ok，我先去尝试，因为我在cf作者底下也反应过这个问题，但是，被作者直接关闭了，说没时间哈哈

果然好了，感谢大佬提醒，终于可以更新新版本了，为了用作者这个插件，一直退回旧版本了

**Comment by 52Hz-p** [comment]
> > > @52Hz-p @7yilink @sa-nny尝试最新的开发分支呢，修复了ComfyUI最新前端导致的bug
> > > ok，我先去尝试，因为我在cf作者底下也反应过这个问题，但是，被作者直接关闭了，说没时间哈哈
> 
> 果然好了，感谢大佬提醒，终于可以更新新版本了，为了用作者这个插件，一直退回旧版本了

如果还是不行，可以删掉插件，重新安装就可以了
