### ISSUE TITLE
COMFYUI更新后打开模型是黑的，什么也不显示

### ISSUE THREAD

**Issue by Lenny5245** [AIGODLIKE/AIGODLIKE-ComfyUI-Studio#45]

**Comment by zangchenyang** [comment]
把插件卸载就能用了，等辣椒酱更新吧。不过目前新的comfui选择模型也挺好用的。

**Comment by Lenny5245** [comment]
主要没有预览图

**Comment by nylenz** [comment]
因为comfyui更新了前端 换ts了，导致这个插件无法使用了

**Comment by KarryCharon** [comment]
@Lenny5245 @nylenz @zangchenyang 
试试最新的develop 分支呢, 修复了ComfyUI 最新前端导致的bug
