### ISSUE TITLE
[Feature requests] Add Model Notes 

### ISSUE THREAD

**Issue by toyxyz** [AIGODLIKE/AIGODLIKE-ComfyUI-Studio#48]
Hi! Thanks for the great work as always. 
I have one feature suggestion. It would be very handy if there was a note function to record trigger words or descriptions of settings for lora or model.

I've created a fork with notes function, but I don't know enough about Java to make pull requests. 

https://github.com/toyxyz/AIGODLIKE-ComfyUI-Studio

![image](https://github.com/user-attachments/assets/598dce5a-bee2-4087-87a4-abe5d6e9dc97)

**Comment by KarryCharon** [comment]
> Hi! Thanks for the great work as always. I have one feature suggestion. It would be very handy if there was a note function to record trigger words or descriptions of settings for lora or model.
> 
> I've created a fork with notes function, but I don't know enough about Java to make pull requests.
> 
> https://github.com/toyxyz/AIGODLIKE-ComfyUI-Studio
> 
> ![image](https://private-user-images.githubusercontent.com/8006000/363736670-598dce5a-bee2-4087-87a4-abe5d6e9dc97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU5NTQwMjcsIm5iZiI6MTcyNTk1MzcyNywicGF0aCI6Ii84MDA2MDAwLzM2MzczNjY3MC01OThkY2U1YS1iZWUyLTQwODctODdhNC1hYmU1ZDZlOWRjOTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTBUMDczNTI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjVlZGE3M2I2MWFkMzhhODI5Y2YwY2ZjMzk2MTY0MjUwNjg5ZTY3ZTc1NTBhMGVjZDY3Zjk5MzU5N2RkNmQyYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.sw5hWnvPoT5PumxX44nhI3At-aV0d-0W20SdI3ZPG30)

WIP

**Comment by KarryCharon** [comment]
@toyxyz New feat pushed. Enjoy!

**Comment by toyxyz** [comment]
> @toyxyz New feat pushed. Enjoy!

Works perfect! Thanks!

![image](https://github.com/user-attachments/assets/96ca4f9b-7670-4f8d-9e2e-9bc7ddff95d0)
