### ISSUE TITLE
【Request】希望可以设定模型预览图大小及备注信息

### ISSUE THREAD

**Issue by amimi818** [AIGODLIKE/AIGODLIKE-ComfyUI-Studio#5]
很棒的扩展！

几点建议供参考：
1.  对于某些节点（如Load Vae等），可选模型不多，也没有预览图，其实并不需要模型加载器。希望能提供是否使用模型加载器的节点选择设置，在支持模型加载器的节点列表中，由使用者自己选择启用模型加载器的节点（未选择节点，节点保持原形态）；
2. 希望可以设置模型预览图大小或显示列数可以再增加一些（目前最多只能显示6列在大屏上还是有点少）；如果预览图显示比例能设置就更好了（很多模型的预览图都不是方形的）；
3.  希望模型能够支持自己添加备注信息，便于记录一些模型的使用说明等信息。虽然可以增加模型工作流预设，但有时候还是直接通过备注信息更加灵活方便；
4.  模型选择页面最好做成弹出窗口或者单独页面，有时候关闭模型选择页面时一不留神就错把ComfyUI主页面也关闭了。

**Comment by Yorha4D** [comment]
@amimi818 
（待讨论）1是否启用它不影响原生列表，依旧可以使用原生
（采纳）2这个的确，在4K屏幕上表现不是很好
（待讨论）3笔记这个功能暂时有工作流，再想想
（待讨论）4可以按Esc退出

**Comment by amimi818** [comment]
> @amimi818 （待讨论）1是否启用它不影响原生列表，依旧可以使用原生 （采纳）2这个的确，在4K屏幕上表现不是很好 （待讨论）3笔记这个功能暂时有工作流，再想想 （待讨论）4可以按Esc退出

感谢回复！
1. 其实还是有些需要的，对于不需要模型加载器的节点，像我这样都有点强迫症的人是很难接受在原生节点上添加一个不太需要的按钮，节点的简洁我想是很多人看中的。

**Comment by Yorha4D** [comment]
@amimi818 讨论过后，觉得开关按钮显示目前不太值得增加代码量和开发时间，暂时不考虑推进。关于显示更多缩略图已经安排了

**Comment by amimi818** [comment]
> @amimi818 讨论过后，觉得开关按钮显示目前不太值得增加代码量和开发时间，暂时不考虑推进。关于显示更多缩略图已经安排了

多谢！

这个问题不知道能否也安排一下：
“另外还有个小问题，启用这个扩展后，那些load节点的默认显示宽度都变小了，不是原生节点的宽度了，不知能否还按原节点宽度显示？”
