### ISSUE TITLE
文件名后缀支持

### ISSUE THREAD

**Issue by zpengcom** [AIGODLIKE/AIGODLIKE-ComfyUI-Studio#9]
之前SD webui里的模型管理里 预览图 格式是：模型名.preview.png
建议支持此后缀 以支持更多插件使用，pysss

**Comment by KarryCharon** [comment]
@zpengcom 最新版已经支持了

**Comment by n714** [comment]
> @zpengcom 最新版已经支持了

后缀.preview.png 还是不显示啊

**Comment by KarryCharon** [comment]
@zpengcom develop分支 是最新的
